AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'spec/**/*'
  TargetRubyVersion: 2.4
  UseCache: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/AbcSize:
  Max: 35

Metrics/ClassLength:
  Max: 150

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Style/AsciiComments:
  Enabled: false

Style/EmptyElse:
  EnforcedStyle: empty

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/TrailingCommaInLiteral:
  Enabled: false
