inherit_mode:
  merge:
    - Include

require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Include:
    - 'lib/**/*'
  Exclude:
    - 'bin/*'
    - 'spec/**/*'
    - 'vendor/**/*'
  NewCops: enable
  TargetRubyVersion: 2.7

Naming/FileName:
  Exclude:
    - 'lib/omniauth-qnyp.rb'

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
