AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'spec/**/*'
  TargetRubyVersion: 2.5
  UseCache: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/AbcSize:
  Max: 35

Metrics/ClassLength:
  Max: 150

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Style/AsciiComments:
  Enabled: false

Style/EmptyElse:
  EnforcedStyle: empty

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false
