version: 2.1

jobs:
  build:
    resource_class: small
    docker:
      - image: cimg/ruby:3.1.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

    environment:
      BUNDLE_PATH: "vendor/bundle"
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      BUNDLE_CLEAN: "true"

    steps:
      - checkout

      - run:
          name: Install latest bundler
          command: |
            gem update --system
            gem install bundler

      - restore_cache:
          keys:
            - v1-gem-{{ checksum "omniauth-qnyp.gemspec"  }}-{{ .Branch }}
            - v1-gem-{{ checksum "omniauth-qnyp.gemspec"  }}
            - v1-gem

      - run:
          name: Install dependencies
          command: bundle install

      - save_cache:
          key: v1-gem-{{ checksum "omniauth-qnyp.gemspec"  }}-{{ .Branch }}
          paths:
            - vendor/bundle

      - run:
          name: run tests (rspec)
          command: bundle exec rake spec
