version: 2.1

jobs:
  build:
    resource_class: small
    docker:
      - image: circleci/ruby:2.6.4
        environment:
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "omniauth-qnyp.gemspec" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Configure Bundler
          command: |
            gem update --system
            gem install bundler

      - run:
          name: install dependencies
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "omniauth-qnyp.gemspec" }}

      # run tests!
      - run:
          name: run tests
          command: bundle exec rake spec
